[general]

[env]

[window]
#decorations = "Full" | "None" | "Transparent" | "Buttonless"
title = "Terminal"
option_as_alt = "Both"

[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
size = 15

[terminal]

