local packpath = vim.fn.stdpath("data") .. "/site"
--vim.opt.rtp:prepend(packpath)
vim.opt.packpath:prepend(packpath)

--require("plugins.snacks")
--require("plugins.noice")
require("plugins.gruvbox")
require("plugins.blink-cmp")
require("plugins.treesitter")
require("plugins.mason")
require("plugins.fzf")
require("plugins.nvim-tree")
--require("plugins.neovim-project")
--require("plugins.project")
--require("plugins.neo-tree")
--require("plugins.fyler")
require("plugins.whichkey")
require("plugins.lualine")
require("plugins.gitsigns")
